### PR TITLE
Updated file to build also windows services

### PR DESCRIPTION
**Pull request by jdetaeye**
The base for the service is only built when the cx_Logging package is found.

It's a real shame that cx_Freeze is maintained sooooo poorly :-(

### CODE REVIEW

**Comment by johnthagen** [comment]
There's also been several new fixes commited to the repo lately: https://bitbucket.org/anthony_tuininga/cx_freeze/commits/all

Would be nice to have wheels posted using the latest trunk.

**Comment by sekrause** [comment]
I've recently updated the wheels to a new build. Which also means that unfortunately I can't merge this request anymore because of conflicts (I also wouldn't really want to merge a pull request with new binaries that I can review).

**Comment by jdetaeye** [comment]
The new files you uploaded still don't have the base executable for running a windows service.  The pull request isn't valid any longer, but the root of the issue hasn't been solved :-(

And issue creation has been disabled on this project :-(

**Comment by sekrause** [comment]
I honestly want to keep this project simple, i.e. just binaries of the 100% unchanged upstream repository. After all it's just supposed to be a temporary project until upstream *finally* releases an official release of 5.0 with binary wheels.

If `bdist_wheel` for some reason doesn't include something that it should include, I think the issue should be reported in the upstream repository: https://bitbucket.org/anthony_tuininga/

**Comment by jdetaeye** [comment]
Fully understand, and won't insist.

FYI: Also my build is a 100% unchanged build from the upstream repository.  However, the build process behaves differently depending on whether the cx_logging library is available or not.
See https://bitbucket.org/anthony_tuininga/cx_freeze/src/ee863267fe9e4f6b638158341a9e635f21699210/setup.py?at=default&fileviewer=file-view-default#setup.py-163 and the definition of the function get_cx_logging at https://bitbucket.org/anthony_tuininga/cx_freeze/src/ee863267fe9e4f6b638158341a9e635f21699210/setup.py?at=default&fileviewer=file-view-default#setup.py-122

**Pull request closed without merging**
